'use strict';
const $ = id => document.getElementById(id);
const guestMode=document.body.dataset.mode==='guest';
const boards = {cake:['케이크 생산','내일의 생산 목록을 확인하고 준비해 주세요.'],notice:['공지사항','매장에 필요한 소식과 안내를 함께 나눠요.'],request:['필요 물품 요청','필요한 물품을 누구나 편하게 요청하세요.']};
let db, board='cake', page=1, member=null, members=[], posts=[], editing=null, viewing=null, media=[], draftQueue=Promise.resolve(), editorOpen=false, mediaBusy=false;
let objectUrls=[], imageIndex=0, originalImage=null, drawing=false;
const uid=()=>crypto.randomUUID ? crypto.randomUUID() : Date.now().toString(36)+Math.random().toString(36).slice(2);
const date=d=>new Date(d).toLocaleString('ko-KR');
const shortDate=d=>new Date(d).toLocaleDateString('ko-KR');
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').hidden=true,4500);}
function store(name, mode, operation){return new Promise((resolve,reject)=>{const tx=db.transaction(name,mode);const req=operation(tx.objectStore(name));let result;req.onsuccess=()=>result=req.result;tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('저장 취소'));});}
const all=name=>store(name,'readonly',s=>s.getAll());
const put=(name,value)=>store(name,'readwrite',s=>s.put(value));
const get=(name,id)=>store(name,'readonly',s=>s.get(id));
const del=(name,id)=>store(name,'readwrite',s=>s.delete(id));
function safeRich(html){const source=new DOMParser().parseFromString(html,'text/html');const allowed=new Set(['B','STRONG','I','EM','U','P','DIV','BR','UL','OL','LI']);function clean(node){if(node.nodeType===3)return document.createTextNode(node.textContent);const out=document.createDocumentFragment();if(node.nodeType!==1)return out;if(['SCRIPT','STYLE','IFRAME','OBJECT'].includes(node.tagName))return out;const target=allowed.has(node.tagName)?document.createElement(node.tagName):out;for(const child of node.childNodes)target.append(clean(child));return target;}const holder=document.createElement('div');for(const node of source.body.childNodes)holder.append(clean(node));return holder.innerHTML;}
function textOf(html){const element=document.createElement('div');element.innerHTML=safeRich(html);return element.textContent;}
function tomorrowTitle(){const d=new Date();d.setDate(d.getDate()+1);return `[${String(d.getFullYear()).slice(-2)}/${String(d.getMonth()+1).padStart(2,'0')}/${String(d.getDate()).padStart(2,'0')}] 생산목록`;}
function currentMember(){return members.find(m=>m.id===member);}
function canRead(){return guestMode||!!currentMember();}
function canWrite(){return guestMode?board==='request':!!currentMember();}
function canEdit(post){return guestMode?post.board==='request'&&!post.member&&post.owner===guestOwner():!!currentMember()&&post.member===member;}
function memberUI(){const user=currentMember();$('loginScreen').hidden=guestMode||!!user;$('appShell').hidden=!canRead();$('account').textContent=guestMode?'비회원 모드 · 회원 로그인':user?`${user.name} · 로그아웃`:'로그인';}
function setRegistrationMode(register){$('memberNameLabel').hidden=!register;$('memberName').disabled=!register;$('memberName').required=register;$('authSubmit').value=register?'register':'login';$('authSubmit').textContent=register?'가입하고 시작하기':'로그인';$('toggleRegistration').textContent=register?'로그인으로 돌아가기':'회원가입';$('loginHeading').textContent=register?'우리 매장 회원가입':'매장 소식 로그인';$('loginDescription').textContent=register?'4자리 회원번호와 이름을 등록하세요.':'등록한 4자리 회원번호를 입력하세요.';$('loginError').textContent='';}
function logout(){sessionStorage.removeItem('tlj-session');member=null;posts=[];document.querySelectorAll('dialog[open]').forEach(d=>d.close());editorOpen=false;revokeUrls();$('posts').replaceChildren();$('memberForm').reset();setRegistrationMode(false);$('loginError').textContent='';memberUI();$('memberCode').focus();}
async function authenticate(action){if(guestMode)return;const id=$('memberCode').value;const name=$('memberName').value.trim();$('loginError').textContent='';if(!/^[0-9]{4}$/.test(id)){$('loginError').textContent='4자리 회원번호를 입력해 주세요.';return;}if(action==='register'&&!name){$('loginError').textContent='회원가입 시 이름을 입력해 주세요.';return;}try{members=await all('members');if(action==='register'){if(members.some(m=>m.id===id)){$('loginError').textContent='이미 등록된 회원번호입니다.';return;}await store('members','readwrite',s=>s.add({id,name}));members=await all('members');}else if(!members.some(m=>m.id===id)){$('loginError').textContent='등록되지 않은 회원번호입니다. 회원가입 후 이용해 주세요.';return;}member=id;sessionStorage.setItem('tlj-session',id);$('memberForm').reset();setRegistrationMode(false);memberUI();await refresh();}catch{$('loginError').textContent='처리하지 못했습니다. 저장 공간을 확인해 주세요.';}}
async function refresh(){posts=canRead()?await all('posts'):[];render();}
function render(){if(!canRead())return;$('newPost').hidden=!canWrite();document.querySelectorAll('[data-board]').forEach(a=>a.classList.toggle('active',a.dataset.board===board));$('breadcrumb').textContent=$('boardTitle').textContent=boards[board][0];$('boardDescription').textContent=boards[board][1];$('listTitle').textContent=boards[board][0]+' 목록';const query=$('search').value.trim().toLocaleLowerCase();const filtered=posts.filter(p=>p.board===board&&(!query||(p.title+' '+(p.board==='notice'?textOf(p.body):p.body)).toLocaleLowerCase().includes(query))).sort((a,b)=>b.created.localeCompare(a.created));const pages=Math.max(1,Math.ceil(filtered.length/30));page=Math.min(page,pages);$('total').textContent=filtered.length;$('posts').replaceChildren();if(!filtered.length){const empty=document.createElement('div');empty.className='empty';empty.innerHTML='<div class="empty-icon">▤</div><h3></h3><p></p>';empty.querySelector('h3').textContent=query?'검색 결과가 없습니다.':'아직 등록된 글이 없습니다.';empty.querySelector('p').textContent=query?'다른 검색어를 입력해 주세요.':'첫 번째 소식을 작성해 주세요.';$('posts').append(empty);}else{const head=document.createElement('div');head.className='row table-head';head.innerHTML='<span class="number">번호</span><span>제목</span><span class="author">작성자</span><span>작성일</span>';$('posts').append(head);filtered.slice((page-1)*30,page*30).forEach((p,index)=>{const row=document.createElement('button');row.className='row';const number=document.createElement('span');number.className='number';number.textContent=filtered.length-(page-1)*30-index;const title=document.createElement('span');title.className='row-title';title.textContent=p.title;const author=document.createElement('span');author.className='author';author.textContent=p.author;const when=document.createElement('time');when.dateTime=p.created;when.textContent=shortDate(p.created);row.append(number,title,author,when);row.onclick=()=>showPost(p.id);$('posts').append(row);});}$('pagination').replaceChildren();function pageButton(label,target,active=false){const b=document.createElement('button');b.textContent=label;b.disabled=target<1||target>pages;if(active)b.setAttribute('aria-current','page');b.onclick=()=>{page=target;render();};$('pagination').append(b);}pageButton('‹',page-1);for(let i=Math.max(1,page-2);i<=Math.min(pages,page+2);i++)pageButton(i,i,i===page);pageButton('›',page+1);}
function revokeUrls(){objectUrls.forEach(URL.revokeObjectURL);objectUrls=[];}
function mediaElement(item){const element=document.createElement(item.kind==='image'?'img':'video');const url=URL.createObjectURL(item.blob);objectUrls.push(url);element.src=url;if(item.kind==='video'){element.controls=true;element.preload='metadata';}else element.alt=item.name;return element;}
function renderAttachments(){revokeUrls();$('attachments').replaceChildren();media.forEach((item,index)=>{const row=document.createElement('div');row.className='attachment';const name=document.createElement('span');name.textContent=item.name;row.append(mediaElement(item),name);if(item.kind==='image'){const edit=document.createElement('button');edit.type='button';edit.textContent='수정 / 그리기';edit.onclick=()=>openImage(index);row.append(edit);}const remove=document.createElement('button');remove.type='button';remove.textContent='삭제';remove.onclick=()=>{media.splice(index,1);renderAttachments();queueDraft();};row.append(remove);$('attachments').append(row);});}
function draftId(){return `${board}:${editing||'new'}:${member||'guest'}`;}
function snapshot(){return {id:draftId(),title:$('postTitle').value,body:board==='notice'?safeRich($('richBody').innerHTML):$('plainBody').value,guest:$('guestName').value,media:[...media]};}
function queueDraft(){if(!editorOpen)return draftQueue;const value=snapshot();$('draftStatus').textContent='임시저장 중…';draftQueue=draftQueue.catch(()=>{}).then(()=>put('drafts',value));draftQueue.then(()=>{$('draftStatus').textContent='임시저장 완료 · 새로고침해도 내용이 유지됩니다.';},()=>{$('draftStatus').textContent='저장 실패 · 저장 공간을 확인하고 내용을 따로 보관해 주세요.';});return draftQueue;}
async function openEditor(post=null){if(!canWrite()||(post&&!canEdit(post))){toast('이 페이지에서는 작성 또는 수정할 수 없습니다.');return;}editing=post?.id||null;const draft=await get('drafts',draftId());const value=draft||post;media=value?.media?[...value.media]:[];$('postTitle').value=value?.title||(board==='cake'?tomorrowTitle():'');$('plainBody').value=board==='notice'?'':value?.body||'';$('richBody').innerHTML=board==='notice'?safeRich(value?.body||''):'';$('guestName').value=value?.guest||'';$('guestLabel').hidden=!!currentMember();$('richBody').hidden=board!=='notice';$('richTools').hidden=board!=='notice';$('plainBody').hidden=board==='notice';$('editorHeading').textContent=post?'게시글 수정':'새 글 작성';$('editorCategory').textContent=boards[board][0];$('savePost').textContent=post?'수정 저장':'게시하기';$('draftStatus').textContent=draft?'저장된 작성 내용을 불러왔습니다.':'작성 내용은 자동으로 임시저장됩니다.';renderAttachments();editorOpen=true;$('editorDialog').showModal();$('postTitle').focus();}
async function closeEditor(){if(mediaBusy){toast('첨부파일 처리 후 닫아 주세요.');return;}try{await queueDraft();editorOpen=false;$('editorDialog').close();revokeUrls();}catch{toast('임시저장에 실패했습니다. 내용을 복사해 보관해 주세요.');}}
async function showPost(id){if(!canRead())return;const post=await get('posts',id);if(!post)return;viewing=post;const printable=post.board==='cake';$('printControls').hidden=!printable;$('printHint').hidden=!printable;$('largeText').checked=printable;$('paperWidth').value='80';$('printArticle').classList.toggle('large',printable);$('printPageStyle')?.remove();$('detailCategory').textContent=boards[post.board][0];$('detailTitle').textContent=post.title;$('detailMeta').textContent=`작성자 ${post.author} · 작성 ${date(post.created)} · 업데이트 ${date(post.updated)}`;if(post.board==='notice')$('detailBody').innerHTML=safeRich(post.body);else $('detailBody').textContent=post.body;revokeUrls();$('detailMedia').replaceChildren(...post.media.map(mediaElement));$('editPost').hidden=!canEdit(post);$('detailDialog').showModal();}
function guestOwner(){let id=localStorage.getItem('tlj-guest');if(!id){id=uid();localStorage.setItem('tlj-guest',id);}return id;}
async function addFile(file,kind){if(!file)return;const types=kind==='image'?['image/png','image/jpeg','image/webp']:['video/mp4','video/webm'];if(!types.includes(file.type)){toast('지원하지 않는 파일 형식입니다.');return;}if(file.size>(kind==='image'?10:50)*1024*1024){toast(kind==='image'?'이미지는 10MB 이하로 첨부해 주세요.':'동영상은 50MB 이하로 첨부해 주세요.');return;}if(media.length>=10){toast('첨부파일은 최대 10개까지 가능합니다.');return;}mediaBusy=true;$('savePost').disabled=true;try{if(kind==='image'){const bitmap=await createImageBitmap(file);const canvas=document.createElement('canvas');const scale=Math.min(1,1800/Math.max(bitmap.width,bitmap.height));canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw Error();media.push({kind,name:file.name,blob});}else media.push({kind,name:file.name,blob:file});renderAttachments();await queueDraft();}catch{toast('첨부 실패 · 파일 또는 브라우저 저장 공간을 확인해 주세요.');}finally{mediaBusy=false;$('savePost').disabled=false;}}
async function drawBlob(blob){const bitmap=await createImageBitmap(blob);const canvas=$('imageCanvas');canvas.width=bitmap.width;canvas.height=bitmap.height;canvas.getContext('2d').drawImage(bitmap,0,0);bitmap.close();}
async function openImage(index){imageIndex=index;originalImage=media[index].blob;try{await drawBlob(originalImage);$('imageDialog').showModal();}catch{toast('이미지를 열 수 없습니다.');}}
function wire(){window.addEventListener('hashchange',()=>{board=boards[location.hash.slice(1)]?location.hash.slice(1):(guestMode?'request':'cake');page=1;$('search').value='';render();});$('search').oninput=()=>{page=1;render();};$('newPost').onclick=()=>openEditor().catch(()=>toast('작성 화면을 열 수 없습니다.'));$('account').onclick=()=>{if(guestMode){location.href='index.html';return;}logout();};document.querySelectorAll('[data-close]').forEach(button=>button.onclick=()=>$(button.dataset.close).close());$('toggleRegistration').onclick=()=>setRegistrationMode($('authSubmit').value!=='register');$('memberForm').onsubmit=async e=>{e.preventDefault();await authenticate(e.submitter?.value||$('authSubmit').value);};['postTitle','plainBody','richBody','guestName'].forEach(id=>$(id).addEventListener('input',queueDraft));$('richBody').addEventListener('paste',e=>{e.preventDefault();document.execCommand('insertText',false,e.clipboardData.getData('text/plain'));queueDraft();});$('richBody').addEventListener('drop',e=>e.preventDefault());document.querySelectorAll('[data-format]').forEach(b=>{b.onmousedown=e=>e.preventDefault();b.onclick=()=>{$('richBody').focus();document.execCommand(b.dataset.format,false);queueDraft();};});$('imageInput').onchange=e=>{addFile(e.target.files[0],'image');e.target.value='';};$('videoInput').onchange=e=>{addFile(e.target.files[0],'video');e.target.value='';};$('closeEditor').onclick=closeEditor;$('editorDialog').addEventListener('cancel',e=>{e.preventDefault();closeEditor();});$('discardDraft').onclick=async()=>{if(mediaBusy)return;if(!confirm('작성 중인 내용을 삭제할까요?'))return;try{await draftQueue.catch(()=>{});await del('drafts',draftId());editorOpen=false;$('editorDialog').close();revokeUrls();toast('임시저장을 삭제했습니다.');}catch{toast('임시저장을 삭제하지 못했습니다.');}};
$('postForm').onsubmit=async e=>{e.preventDefault();if(mediaBusy||!canWrite())return;const value=snapshot();if(!value.title.trim()||!(board==='notice'?textOf(value.body):value.body).trim()&&!media.length){toast('제목과 내용을 입력해 주세요.');return;}$('savePost').disabled=true;try{await queueDraft();const previous=editing?await get('posts',editing):null;if(editing&&(!previous||!canEdit(previous)))throw Error('권한 없음');const user=currentMember();const now=new Date().toISOString();const post={id:editing||uid(),board,title:value.title.trim(),body:value.body,media:[...media],created:previous?.created||now,updated:now,author:previous?.author||user?.name||value.guest.trim()||'비회원',member:previous?.member||member,owner:previous?.owner||guestOwner()};await put('posts',post);await del('drafts',draftId());editorOpen=false;$('editorDialog').close();revokeUrls();await refresh();toast('게시글을 저장했습니다.');}catch{toast('저장하지 못했습니다. 저장 공간을 확인해 주세요.');}finally{$('savePost').disabled=false;}};
$('editPost').onclick=()=>{$('detailDialog').close();openEditor(viewing).catch(()=>toast('수정 화면을 열 수 없습니다.'));};$('largeText').onchange=e=>$('printArticle').classList.toggle('large',e.target.checked);$('printPost').onclick=()=>{if(viewing?.board!=='cake')return;let style=$('printPageStyle');if(!style){style=document.createElement('style');style.id='printPageStyle';document.head.append(style);}const width=Number($('paperWidth').value);style.textContent=`@media print { @page { size: ${width}mm 297mm; margin: 3mm; } #printArticle { width: ${width-6}mm; max-width:100%; } }`;window.print();};
const canvas=$('imageCanvas');const point=e=>{const r=canvas.getBoundingClientRect();return [(e.clientX-r.left)*canvas.width/r.width,(e.clientY-r.top)*canvas.height/r.height];};canvas.onpointerdown=e=>{drawing=true;canvas.setPointerCapture(e.pointerId);const context=canvas.getContext('2d');context.beginPath();context.moveTo(...point(e));context.strokeStyle=$('penColor').value;context.lineWidth=Number($('penSize').value)*canvas.width/canvas.clientWidth;context.lineCap='round';context.lineJoin='round';};canvas.onpointermove=e=>{if(!drawing)return;const context=canvas.getContext('2d');context.lineTo(...point(e));context.stroke();};canvas.onpointerup=canvas.onpointercancel=()=>drawing=false;$('rotateImage').onclick=()=>{const copy=document.createElement('canvas');copy.width=canvas.width;copy.height=canvas.height;copy.getContext('2d').drawImage(canvas,0,0);canvas.width=copy.height;canvas.height=copy.width;const context=canvas.getContext('2d');context.translate(canvas.width,0);context.rotate(Math.PI/2);context.drawImage(copy,0,0);context.setTransform(1,0,0,1,0,0);};$('resetImage').onclick=()=>drawBlob(originalImage);$('applyImage').onclick=()=>{canvas.toBlob(async blob=>{if(!blob){toast('이미지를 저장하지 못했습니다.');return;}media[imageIndex]={...media[imageIndex],blob};renderAttachments();$('imageDialog').close();await queueDraft().catch(()=>toast('임시저장 실패 · 저장 공간을 확인해 주세요.'));},'image/png');};window.addEventListener('beforeunload',e=>{if(mediaBusy||$('draftStatus').textContent==='임시저장 중…'){e.preventDefault();e.returnValue='';}});}
(async()=>{try{db=await new Promise((resolve,reject)=>{const req=indexedDB.open('tlj-notice',1);req.onupgradeneeded=()=>{for(const name of ['posts','members','drafts'])req.result.createObjectStore(name,{keyPath:'id'});};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});members=await all('members');member=guestMode?null:sessionStorage.getItem('tlj-session')||null;if(!currentMember())member=null;board=boards[location.hash.slice(1)]?location.hash.slice(1):(guestMode?'request':'cake');wire();memberUI();await refresh();window.dispatchEvent(new Event('tlj:ready'));}catch{toast('브라우저 저장소를 사용할 수 없습니다. 일반 브라우저 모드에서 다시 열어 주세요.');$('newPost').disabled=true;$('account').disabled=true;}})();

