const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const root=path.join(__dirname,'../frontend');
const source=name=>fs.readFileSync(path.join(root,'js',name),'utf8');
function context(dataset={}){
  const nodes=new Map(), redirects=[], session=new Map();
  function node(id){if(!nodes.has(id))nodes.set(id,{value:'',textContent:'',hidden:false,disabled:false,innerHTML:'',classList:{toggle(){}},replaceChildren(){},append(){},focus(){},addEventListener(){},showModal(){this.open=true},close(){this.open=false},querySelector(){return node(id+'child')}});return nodes.get(id);}
  const c=vm.createContext({document:{body:{dataset},getElementById:node,querySelectorAll:()=>[],createElement:()=>node('created')},sessionStorage:{getItem:k=>session.get(k)||null,setItem:(k,v)=>session.set(k,v),removeItem:k=>session.delete(k)},localStorage:{getItem:()=> 'guest-owner'},location:{search:'',pathname:'/notice.html',replace:p=>redirects.push(p)},window:{addEventListener(){},dispatchEvent(){}},URLSearchParams,Event,crypto:{randomUUID:()=> 'id'},URL:{revokeObjectURL(){}},setTimeout:()=>0,clearTimeout(){}});
  vm.runInContext(source('common.js'),c);
  return {c,node,redirects,session,run:s=>vm.runInContext(s,c)};
}
const tick=()=>new Promise(resolve=>setImmediate(resolve));
(async()=>{
  for(const file of fs.readdirSync(root).filter(f=>f.endsWith('.html'))){
    const html=fs.readFileSync(path.join(root,file),'utf8');
    for(const [,target] of html.matchAll(/(?:href|src)="([^"]+)"/g))assert.ok(fs.existsSync(path.join(root,target.split(/[?#]/)[0])),`${file}: ${target}`);
    const ids=[...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]);assert.equal(ids.length,new Set(ids).size);
  }
  assert.ok(!fs.readFileSync(path.join(root,'login.html'),'utf8').includes('id="memberName"'));
  assert.ok(fs.readFileSync(path.join(root,'register.html'),'utf8').includes('id="memberName"'));
  console.log('PASS page links, unique IDs and separate login/registration forms');
  const login=context({page:'login'});
  login.run("initializeStore=async()=>{};store=async()=>[{id:'0123',name:'회원'}];");
  login.run(source('auth.js'));await tick();
  login.node('memberCode').value='9999';await login.run('authenticate()');assert.equal(login.redirects.length,0);
  login.node('memberCode').value='0123';await login.run('authenticate()');assert.equal(login.session.get('tlj-session'),'0123');assert.equal(login.redirects.at(-1),'cake.html');
  console.log('PASS number-only login and unknown member rejection');
  const registration=context({page:'register'});
  registration.run("initializeStore=async()=>{};store=async(name,mode)=>mode==='readonly'?[]:undefined;");
  registration.run(source('auth.js'));await tick();
  registration.node('memberCode').value='0123';await registration.run('authenticate()');assert.equal(registration.redirects.length,0);
  registration.node('memberName').value='회원';await registration.run('authenticate()');assert.equal(registration.session.get('tlj-session'),'0123');
  console.log('PASS registration requires name and preserves leading zero');
  const member=context({mode:'member',board:'notice'});
  member.run('initializeStore=async()=>{};');member.run(source('board.js'));await tick();
  assert.equal(member.redirects[0],'login.html?next=notice.html');
  console.log('PASS direct member board redirects to login');
  const guest=context({mode:'guest',board:'request'});
  guest.run("member='0123';members=[{id:'0123',name:'회원'}];initializeStore=async()=>{member=null};store=async()=>[];wireEditor=()=>{};wireDetail=()=>{};");
  guest.run(source('board.js'));await tick();assert.equal(guest.redirects.length,0);assert.equal(guest.run('member'),null);assert.equal(guest.run('canWrite()'),true);
  guest.run("board='cake'");assert.equal(guest.run('canWrite()'),false);
  guest.run("board='notice'");assert.equal(guest.run('canWrite()'),false);
  console.log('PASS guest identity and request-only writing');
  guest.node('printPageStyle').remove=()=>{};
  guest.run(source('detail.js'));
  guest.run("store=async()=>({id:'1',board:'cake',title:'생산',body:'내용',media:[],created:new Date().toISOString(),updated:new Date().toISOString()});");
  await guest.run("showPost('1')");assert.equal(guest.node('largeText').checked,true);assert.equal(guest.node('paperWidth').value,'80');assert.equal(guest.node('printControls').hidden,false);
  guest.run("store=async()=>({id:'2',board:'notice',title:'공지',body:'',media:[],created:new Date().toISOString(),updated:new Date().toISOString()});safeRich=html=>html;");
  await guest.run("showPost('2')");assert.equal(guest.node('printControls').hidden,true);assert.equal(guest.node('printHint').hidden,true);
  console.log('PASS cake print defaults and notice print controls hidden');
  guest.run(source('editor.js'));
  guest.run("board='request';store=async()=>({title:'임시 요청',body:'봉투',guest:'손님',media:[]});renderAttachments=()=>{};");
  await guest.run('openEditor()');assert.equal(guest.node('postTitle').value,'임시 요청');assert.equal(guest.node('plainBody').value,'봉투');
  console.log('PASS draft restoration after script separation');
  const anonymousProfile=context({mode:'member'});
  anonymousProfile.run('initializeStore=async()=>{};');
  anonymousProfile.run(source('profile.js'));await tick();
  assert.equal(anonymousProfile.redirects[0],'login.html?next=profile.html');
  const profile=context({mode:'member'});
  profile.session.set('tlj-session','0123');
  profile.run("initializeStore=async()=>{member='0123';members=[{id:'0123',name:'기존 이름'}]};let savedProfile={id:'0123',name:'기존 이름'};store=async(name,mode,operation)=>mode==='readonly'?savedProfile:operation({put:value=>{savedProfile=value}});");
  profile.run(source('profile.js'));await tick();
  assert.equal(profile.node('profileCode').value,'0123');
  assert.equal(profile.node('profileName').value,'기존 이름');
  profile.node('profileName').value='   ';await profile.run('saveProfile()');assert.equal(profile.run('savedProfile.name'),'기존 이름');
  profile.node('profileName').value='가'.repeat(31);await profile.run('saveProfile()');assert.equal(profile.run('savedProfile.name'),'기존 이름');
  profile.node('profileCode').value='9999';profile.node('profileName').value=' 새 이름 ';await profile.run('saveProfile()');
  assert.equal(profile.run('savedProfile.id'),'0123');assert.equal(profile.run('savedProfile.name'),'새 이름');assert.equal(profile.run('currentMember().name'),'새 이름');
  profile.run("store=async()=>{throw Error('storage full')}");profile.node('profileName').value='실패';await profile.run('saveProfile()');assert.equal(profile.run('currentMember().name'),'새 이름');assert.ok(profile.node('profileError').textContent);
  profile.session.delete('tlj-session');await profile.run('saveProfile()');assert.equal(profile.redirects.at(-1),'login.html?next=profile.html');
  console.log('PASS profile access, name validation, persistence, fixed member ID and failure handling');
  const permissions=context({mode:'member'});
  permissions.run("member='1234';members=[{id:'1234',name:'일반 회원'}];");
  for(const key of ['cake','notice','request']) {
    permissions.run(`board='${key}'`);
    assert.equal(permissions.run('canRead()'),true);
    assert.equal(permissions.run('canWrite()'),key==='request');
    assert.equal(permissions.run(`canEdit({board:'${key}',member:'9999'})`),key==='request');
    assert.equal(permissions.run(`canDelete({board:'${key}',member:'9999'})`),key==='request');
  }
  permissions.run("members[0].permissions=defaultPermissions();members[0].permissions.cake={read:false,write:false,edit:true,delete:false};board='cake';");
  assert.equal(permissions.run('canRead()'),false);
  assert.equal(permissions.run("canEdit({board:'cake'})"),true);
  assert.equal(permissions.run('isUserAdmin()'),false);
  console.log('PASS existing-member defaults and independent board permissions');
  const admin=context({mode:'member'});admin.session.set('tlj-session','0026');
  admin.run("const records=new Map([['0026',{id:'0026',name:'관리자'}],['1234',{id:'1234',name:'회원'}]]);initializeStore=async()=>{member='0026';members=[...records.values()]};store=async(name,mode,op)=>op({get:id=>records.get(id),put:value=>records.set(value.id,value)});");
  admin.run(source('users.js'));admin.run('renderUsers=()=>{}');await tick();
  await admin.run("updateUser('1234',' 새 이름 ',{...defaultPermissions(),cake:{read:true,write:true,edit:true,delete:true}})");
  assert.equal(admin.run("records.get('1234').name"),'새 이름');
  assert.equal(admin.run("records.get('1234').permissions.cake.delete"),true);
  await assert.rejects(admin.run("updateUser('1234',' ',defaultPermissions())"));
  await assert.rejects(admin.run("updateUser('1234','이름',{cake:{read:true}})"));
  admin.session.set('tlj-session','1234');
  await assert.rejects(admin.run("updateUser('0026','변조',defaultPermissions())"));
  assert.equal(admin.run("records.get('0026').name"),'관리자');
  assert.equal(admin.redirects.at(-1),'cake.html');
  console.log('PASS 0026-only management, user rename, permission save and invalid input rejection');
  const editor=context({mode:'member'});editor.session.set('tlj-session','1234');
  editor.run("const records={members:{id:'1234',name:'회원',permissions:defaultPermissions()},posts:{id:'post',board:'request',member:'9999',title:'요청',body:'내용',media:[],created:'2026-01-01',updated:'2026-01-01'}};member='1234';members=[records.members];board='request';let deleted=false;store=async(name,mode,op)=>op({get:()=>records[name],delete:()=>{deleted=true},put:()=>{}});revokeUrls=()=>{};refresh=async()=>{};confirm=()=>true;");
  editor.run(source('editor.js'));editor.run('renderAttachments=()=>{}');
  editor.run('records.members.permissions.request.write=false;');
  await editor.run('openEditor(records.posts)');assert.equal(editor.run('editorOpen'),true);
  editor.run("records.members.permissions.request.edit=false;editorOpen=false;");
  await editor.run('openEditor(records.posts)');assert.equal(editor.run('editorOpen'),false);
  editor.run(source('detail.js'));editor.run('viewing=records.posts;records.members.permissions.request.delete=false;');
  await editor.run('deleteCurrentPost()');assert.equal(editor.run('deleted'),false);
  editor.run('records.members.permissions.request.delete=true;');
  await editor.run('deleteCurrentPost()');assert.equal(editor.run('deleted'),true);
  console.log('PASS edit without write permission, live revocation and authorized deletion');
})().catch(e=>{console.error(e);process.exitCode=1});
